In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import fetch_openml # delete

def load() -> pd.DataFrame:

        dataset_id = 42585

        data_raw = fetch_openml(data_id=dataset_id, as_frame=True)
        df = data_raw.frame
        df = df.dropna()

        return df

In [16]:
df = load()
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE

In [17]:
df["species"].unique()

['Adelie', 'Chinstrap', 'Gentoo']
Categories (3, object): ['Adelie', 'Chinstrap', 'Gentoo']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 334 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            334 non-null    category
 1   island             334 non-null    category
 2   culmen_length_mm   334 non-null    float64
 3   culmen_depth_mm    334 non-null    float64
 4   flipper_length_mm  334 non-null    float64
 5   body_mass_g        334 non-null    float64
 6   sex                334 non-null    category
dtypes: category(3), float64(4)
memory usage: 14.4 KB

In [9]:
col = df.dtypes == "category"
col

species               True
island                True
culmen_length_mm     False
culmen_depth_mm      False
flipper_length_mm    False
body_mass_g          False
sex                   True
dtype: bool

In [18]:
mapping = {"Adelie": 0, "Chinstrap": 1, "Gentoo": 2}
df["species"] = df["species"].astype(str).str.strip().map(mapping)
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,0,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,0,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,0,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,0,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,0,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,2,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,2,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,2,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,2,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,2,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
import joblib

model_path = "../models/model.pkl"
model = joblib.load(model_path)

In [34]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 3,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 5,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 50,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}